apiVersion: v1
kind: Pod
metadata:
  name: dev-box
  namespace: alchemist-processor
  labels:
    app: dev-box
  annotations:
    iam.amazonaws.com/role: svc-sandbox-alchemist
spec:
  containers:
  - name:  dev-box
    image: opendatacube/datacube-alchemist:latest
    #args: ["/usr/bin/env", "sleep", "60000"]
    resources:
      requests:
        cpu: 1.5
        memory: 8072Mi
      limits:
        cpu: 2
        memory: 8096Mi
    tty: true
    stdin: true
    env:
    - name: AWS_DEFAULT_REGION
      valueFrom:
        secretKeyRef:
          name: svc-sandbox-alchemist
          key: AWS_DEFAULT_REGION
    - name: ALCHEMIST_ADDTOQUEUE_MESSAGE_QUEUE
      value: "alchemist-standard-test"
    - name: ALCHEMIST_ADDTOQUEUE_ENVIRONMENT
      value: "datacube"
    - name: ALCHEMIST_ADDTOQUEUE_LIMIT
    # Here's the LIMIT! 
      value: "9000000"
    - name: ALCHEMIST_PROCESSQUEUE_MESSAGE_QUEUE
      value: "alchemist-standard"
    - name: ALCHEMIST_PROCESSQUEUE_SQS_TIMEOUT
      value: "900"
    - name: ALCHEMIST_ADDTOQUEUE_CONFIG_FILE
    # Need to add both A and B
      # value: "https://raw.githubusercontent.com/opendatacube/datacube-alchemist/master/examples/fc_config_sentinel2a_alex.yaml"
      value: "https://raw.githubusercontent.com/opendatacube/datacube-alchemist/master/examples/fc_config_sentinel2a_dsg_test.yaml"
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: sandbox-datacube
          key: postgres-username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: sandbox-datacube
          key: postgres-password
    - name: DATACUBE_CONFIG_PATH
      value: "/opt/custom-config.conf"
    - name: DB_DATABASE
      value: "sandbox"
    - name: DB_HOSTNAME
      value: "database.local"
    - name: DB_PORT
      value: "5432"
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: svc-sandbox-alchemist
          key: AWS_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: svc-sandbox-alchemist
          key: AWS_SECRET_ACCESS_KEY
    - name: LOG_LEVEL
      value: "INFO"
    command: ["/bin/sh", "-ec", "docker-entrypoint.sh && while :; do echo '.'; sleep 5 ; done"]
  nodeSelector:
    beta.kubernetes.io/os: linux
  restartPolicy: Never
