apiVersion: apps/v1
kind: Deployment
metadata:
  name: alchemist-processqueue
  namespace: alchemist-processor
  labels:
    app: alchemist-processqueue
spec:
  replicas: 10
  selector:
    matchLabels:
      app: alchemist-processqueue
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: svc-sandbox-alchemist
      labels:
        app: alchemist-processqueue
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodetype
                    operator: In
                    values:
                      - spot
      containers:
      - name: alchemist-processor-container
        image: opendatacube/datacube-alchemist
        command: [ "datacube-alchemist", "processqueue" ]
        resources:
          requests:
            cpu: 1.5
            memory: 3072Mi
          limits:
            cpu: 2.0
            memory: 4096Mi
        tty: true
        stdin: true
        env:
        - name: ALCHEMIST_PROCESSQUEUE_MESSAGE_QUEUE
          value: "alchemist-standard-test"
        - name: ALCHEMIST_PROCESSQUEUE_SQS_TIMEOUT
          value: "900"
        - name: AWS_DEFAULT_REGION
          value: ap-southeast-2
        - name: DATACUBE_CONFIG_PATH
          value: "/opt/custom-config.conf"
        - name: DB_DATABASE
          value: "sandbox"
        - name: DB_HOSTNAME
          value: "database.local"
        - name: DB_PORT
          value: "5432"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: sandbox-datacube
              key: postgres-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sandbox-datacube
              key: postgres-password
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: svc-sandbox-alchemist
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: svc-sandbox-alchemist
              key: AWS_SECRET_ACCESS_KEY
